# Generated by Django 5.0.4 on 2024-05-15 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_permission'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Permission',
        ),
    ]
